require "autocmds"
require "colors"
require "keymaps"
require "lsp"
require "options"
require "treesitter"

require "plugins.autopairs"
require "plugins.emmet"
require "plugins.lualine"
require "plugins.mason"
require "plugins.nerdtree"
require "plugins.nvim-cmp"
require "plugins.packer"
require "plugins.sneak"
require "plugins.surround"
require "plugins.symbols-outline"
require "plugins.telescope"
require "plugins.vim-vsnip"

require "utils.runners"
