require "autocmds"
require "colors"
require "keymaps"
require "lsp"
require "options"
require "treesitter"

require "plugins.autopairs"
require "plugins.cmp"
require "plugins.emmet"
require "plugins.lsp-signature"
require "plugins.lualine"
require "plugins.luasnip"
require "plugins.mason"
require "plugins.nerdtree"
require "plugins.null-ls"
require "plugins.packer"
require "plugins.sneak"
require "plugins.surround"
require "plugins.symbols-outline"
require "plugins.telescope"

require "utils.runners"
