require("didorgas.options")
require("didorgas.colors")
require("didorgas.keymaps")
require("didorgas.lsp")
require("didorgas.runner")

-- Plugins configurations
require("didorgas.plugins.cmp")
require("didorgas.plugins.mason")
require("didorgas.plugins.packer")
require("didorgas.plugins.smalls")
require("didorgas.plugins.surround")
require("didorgas.plugins.tagbar")
require("didorgas.plugins.telescope")
require("didorgas.plugins.tree")
