require("didorgas.colors")
require("didorgas.keymaps")
require("didorgas.lsp")
require("didorgas.options")
require("didorgas.runner")
require("didorgas.packer")

-- Plugins configurations
require("didorgas.plugins.cmp")
require("didorgas.plugins.emmet")
require("didorgas.plugins.lualine")
require("didorgas.plugins.mason")
require("didorgas.plugins.nerdtree")
require("didorgas.plugins.sneak")
require("didorgas.plugins.surround")
require("didorgas.plugins.tagbar")
require("didorgas.plugins.telescope")
require("didorgas.plugins.vsnip")

-- require("didorgas.plugins.null-ls")
-- require("didorgas.plugins.toggleterm")
